# Generated by Django 5.2.3 on 2025-06-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='machines',
            field=models.ManyToManyField(blank=True, to='factory_app.machine'),
        ),
    ]
