# Generated by Django 5.2.3 on 2025-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0002_man_machines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='man',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='man',
            name='user',
        ),
        migrations.AddField(
            model_name='man',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='man',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='man',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='man',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
